### ISSUE TITLE
Moving to the cake-contrib organization

### ISSUE THREAD

**Issue by ecampidoglio** [cake-contrib/Cake.Curl#29]
In order to guarantee the future maintenance of Cake.Curl (and to align it with the other Cake addins), I'm moving this repo to the cake-contrib organization. I'll still be the primary maintainer of the project, but I won't be the _only_ maintainer. 😉

While the transfer process is [well documented](https://github.com/cake-contrib/Home#how-do-i-as-an-addin-author-transfer-a-repository-to-the-organisation) and pretty straightforward, there are a few things that must be taken care of for it to happen:

- [x] Transfer the repo to @gep13
- [x] Create an [AppVeyor](https://www.appveyor.com/) project under the cake-contrib account
- [x] Create a [Travis CI](https://travis-ci.org/) project under the [cake-contrib](https://travis-ci.org/cake-contrib) account
- [x] Update the URLs of the repository in the [project file](https://github.com/ecampidoglio/Cake.Curl/blob/master/src/Cake.Curl/Cake.Curl.csproj#L20-L23)
- [x] Update the URL of the build status badges in the [README file](https://github.com/ecampidoglio/Cake.Curl/blob/master/README.md)
- [x] Update the URLs in this [file](https://github.com/cake-build/website/blob/develop/addins/Cake.Curl.yml)
- [x] Let @gep13 know the best email address to use for adding you to a Slack Team

I'll add new items as they come up.

**Comment by gep13** [comment]
@ecampidoglio AppVeyor Project is here: https://ci.appveyor.com/project/cakecontrib/cake-curl

The permission sync tool that we have is still running, so you might not have permissions to this just yet.

**Comment by gep13** [comment]
@ecampidoglio you should now be able to access the repository which is here: https://github.com/cake-contrib/Cake.Curl

**Comment by gep13** [comment]
Travis CI build is here: https://travis-ci.org/cake-contrib/Cake.Curl

**Comment by ecampidoglio** [comment]
All tasks are completed. ✅
