### ISSUE TITLE
Generic way to add missing options?

### ISSUE THREAD

**Issue by WayneHiller** [cake-contrib/Cake.Curl#38]
Is there any way to specify curl options that are not listed in the CurlSettings class? I need to add --ftp-create-dirs.  If not should there be a generic way to manually specify arguments?

**Comment by ecampidoglio** [comment]
Sure, you can use the [`ArgumentCustomization`](https://cakebuild.net/api/Cake.Core.Tooling/ToolSettings/50AAB3A8) property of the `CurlSettings` class to pass any arguments to curl.

Here's how you would pass the `--ftp-create-dirs` switch:

```csharp
var settings = new CurlSettings
{
    ArgumentCustomization = args => args.Append("--ftp-create-dirs");
}
```

Have a look at the extension methods of the [`ProcessArgumentBuilder`](https://cakebuild.net/api/Cake.Core.IO/ProcessArgumentBuilder/) class to see the different ways you can specify custom arguments to an underlying command line tool.

**Comment by WayneHiller** [comment]
Excellent, that works great, Thank you
